let
    DataMin= List.Min(#"Base Vendas"[Data da Venda]),
    DataMax = List.Max(#"Base Vendas"[Data da Venda]),
    QntDias = Duration.Days(DataMax-DataMin)+1,
    Diarias = List.Dates(DataMin, QntDias, #duration(1, 0, 0, 0)),
    #"Converted to Table" = Table.FromList(Diarias, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Data Diárias"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Data Diárias", type date}}),
    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Data Diárias]), Int64.Type),
    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Data Diárias]), Int64.Type),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted Month", "Month Name", each Date.MonthName([Data Diárias]), type text),
    #"Capitalized Each Word" = Table.TransformColumns(#"Inserted Month Name",{{"Month Name", Text.Proper, type text}}),
    #"Inserted Start of Month" = Table.AddColumn(#"Capitalized Each Word", "Start of Month", each Date.StartOfMonth([Data Diárias]), type date),
    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Start of Month", "Start of Quarter", each Date.StartOfQuarter([Data Diárias]), type date),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Start of Quarter", "Week of Year", each Date.WeekOfYear([Data Diárias]), Int64.Type)
in
    #"Inserted Week of Year"